name: weak_collections
description: Collection of soft references. Weak reference effect achieved through WeakReference and Finalizer.
version: 1.2.0
repository: https://github.com/aymtools/weak_collections

environment:
  sdk: '>=2.17.0 <4.0.0'

