name: weak_collections
description: Collection of weak references. WeakHashMap, WeakLinkedHashMap, WeakHashSet, WeakLinkedHashSet, WeakQueue. Weak reference effect achieved through WeakReference and Finalizer.
version: 1.6.1
homepage: https://github.com/aymtools/weak_collections

topics:
  - weak
  - weak-hashmap
  - weak-hashset
  - weak-queue
  - weak-linked-hashmap

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: any
  test: ^1.5.1
  vm_service: any
#  vm_service: ^15.0.2
