name: weak_collections
description: Collection of soft references. Weak reference effect achieved through WeakReference and Finalizer.
version: 1.2.1
repository: https://github.com/aymtools/weak_collections

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  test: ^1.25.14
